//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le numéro ISBN doit contenir 10 ou 13 chiffres.
        /// </summary>
        internal static string AddBookFromAmazon_FindBookByIsbn_Le_numéro_ISBN_doit_contenir_10_ou_13_chiffres {
            get {
                return ResourceManager.GetString("AddBookFromAmazon_FindBookByIsbn_Le_numéro_ISBN_doit_contenir_10_ou_13_chiffres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de l&apos;insertion du livre..
        /// </summary>
        internal static string CreateLivre_btnCreate_Click_Erreur_lors_de_l_insertion_du_livre_ {
            get {
                return ResourceManager.GetString("CreateLivre_btnCreate_Click_Erreur_lors_de_l_insertion_du_livre_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la récupération des informations sur le livre demandé..
        /// </summary>
        internal static string DashboardManager_loadFicheLivre_Erreur_lors_de_la_recuperation_des_informations_sur_le_livre_demande_ {
            get {
                return ResourceManager.GetString("DashboardManager_loadFicheLivre_Erreur_lors_de_la_recuperation_des_informations_s" +
                        "ur_le_livre_demande_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le livre n&apos;a pas pu etre ajouté dans votre liste de demande.
        /// </summary>
        internal static string DashboardManager_totoToolStripMenuItem_Click_Le_livre_n_a_pas_pu_etre_ajoute_dans_votre_liste_de_demande {
            get {
                return ResourceManager.GetString("DashboardManager_totoToolStripMenuItem_Click_Le_livre_n_a_pas_pu_etre_ajoute_dans" +
                        "_votre_liste_de_demande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec lors de l&apos;enregistrement de l&apos;emprunt.
        /// </summary>
        internal static string EmpruntManagement_btnValider_Click_Echec_lors_de_l_enregistrement_de_l_emprunt {
            get {
                return ResourceManager.GetString("EmpruntManagement_btnValider_Click_Echec_lors_de_l_enregistrement_de_l_emprunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les champs ne sont pas remplis!.
        /// </summary>
        internal static string EmpruntManagement_btnValider_Click_Tous_les_champs_ne_sont_pas_remplis_ {
            get {
                return ResourceManager.GetString("EmpruntManagement_btnValider_Click_Tous_les_champs_ne_sont_pas_remplis_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez trop de livre empruntés. Seul 3 maximum sont authorizés.
        /// </summary>
        internal static string EmpruntManagement_btnValider_Click_Vous_avez_trop_de_livre_empruntes__Seul_3_maximum_sont_authorizes {
            get {
                return ResourceManager.GetString("EmpruntManagement_btnValider_Click_Vous_avez_trop_de_livre_empruntes__Seul_3_maxi" +
                        "mum_sont_authorizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la récupération des informations sur le livre demandé..
        /// </summary>
        internal static string EmpruntManagement_SearchLivreField_Erreur_lors_de_la_recuperation_des_informations_sur_le_livre_demande_ {
            get {
                return ResourceManager.GetString("EmpruntManagement_SearchLivreField_Erreur_lors_de_la_recuperation_des_information" +
                        "s_sur_le_livre_demande_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la récupération des informations sur la réservation demandée.
        /// </summary>
        internal static string EmpruntManagement_SearchReservationField_Erreur_lors_de_la_recuperation_des_informations_sur_la_reservation_demandee {
            get {
                return ResourceManager.GetString("EmpruntManagement_SearchReservationField_Erreur_lors_de_la_recuperation_des_infor" +
                        "mations_sur_la_reservation_demandee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez déjà un Dashboard ouvert.
        /// </summary>
        internal static string FrmMdi_ShowClientDashboard_Vous_avez_deja_un_Dashboard_ouvert {
            get {
                return ResourceManager.GetString("FrmMdi_ShowClientDashboard_Vous_avez_deja_un_Dashboard_ouvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais nom d&apos;utilisateur ou de mot de passe.
        /// </summary>
        internal static string LoginForm_ConnectionResult_Mauvais_nom_d_utilisateur_ou_de_mot_de_passe {
            get {
                return ResourceManager.GetString("LoginForm_ConnectionResult_Mauvais_nom_d_utilisateur_ou_de_mot_de_passe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les champs Nom d&apos;utilisateur et Mot de passe doivent etre remplis!.
        /// </summary>
        internal static string LoginForm_InitConnection_Les_champs_Nom_d_utilisateur_et_Mot_de_passe_doivent_etre_remplis_ {
            get {
                return ResourceManager.GetString("LoginForm_InitConnection_Les_champs_Nom_d_utilisateur_et_Mot_de_passe_doivent_etr" +
                        "e_remplis_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de votre demande d&apos;annulation.
        /// </summary>
        internal static string ReservationManagement_btnAnnuler_Click_Erreur_lors_de_votre_demande_d_annulation {
            get {
                return ResourceManager.GetString("ReservationManagement_btnAnnuler_Click_Erreur_lors_de_votre_demande_d_annulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la récupération des réservations.
        /// </summary>
        internal static string ReservationManagement_cmbReservationToogle_SelectedIndexChanged_Erreur_lors_de_la_recuperation_des_reservations {
            get {
                return ResourceManager.GetString("ReservationManagement_cmbReservationToogle_SelectedIndexChanged_Erreur_lors_de_la" +
                        "_recuperation_des_reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la récupération des informations sur le livre demandé..
        /// </summary>
        internal static string ReservationManagement_GetPersonne_Erreur_lors_de_la_recuperation_des_informations_sur_le_livre_demande_ {
            get {
                return ResourceManager.GetString("ReservationManagement_GetPersonne_Erreur_lors_de_la_recuperation_des_informations" +
                        "_sur_le_livre_demande_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce livre est déjà dans votre liste de demande de réservation.
        /// </summary>
        internal static string SearchLivre_btnSelection_Click_Ce_livre_est_déjà_dans_votre_liste_de_demande_de_réservation {
            get {
                return ResourceManager.GetString("SearchLivre_btnSelection_Click_Ce_livre_est_déjà_dans_votre_liste_de_demande_de_r" +
                        "éservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande de réservation.
        /// </summary>
        internal static string SearchLivre_btnSelection_Click_Demande_de_réservation {
            get {
                return ResourceManager.GetString("SearchLivre_btnSelection_Click_Demande_de_réservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de l&apos;enregistrement de la demande de réservation.
        /// </summary>
        internal static string SearchLivre_btnSelection_Click_Erreur_lors_de_l_enregistrement_de_la_demande_de_réservation {
            get {
                return ResourceManager.GetString("SearchLivre_btnSelection_Click_Erreur_lors_de_l_enregistrement_de_la_demande_de_r" +
                        "éservation", resourceCulture);
            }
        }
    }
}
