//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WebsIFAC/AdministrateurIFAC", ConfigurationName="WCF.Proxies.AdministrateurIFAC")]
    public interface AdministrateurIFAC
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/AdministrateurIFAC/AdministrateurIFAC/SelectById", ReplyAction="urn:WebsIFAC/AdministrateurIFAC/AdministrateurIFAC/SelectByIdResponse")]
        WebsBO.AdministrateurBO SelectById(int pAdministrateurId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/AdministrateurIFAC/AdministrateurIFAC/SelectById", ReplyAction="urn:WebsIFAC/AdministrateurIFAC/AdministrateurIFAC/SelectByIdResponse")]
        System.IAsyncResult BeginSelectById(int pAdministrateurId, System.AsyncCallback callback, object asyncState);
        
        WebsBO.AdministrateurBO EndSelectById(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdministrateurIFACChannel : WCF.Proxies.AdministrateurIFAC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministrateurIFACClient : System.ServiceModel.ClientBase<WCF.Proxies.AdministrateurIFAC>, WCF.Proxies.AdministrateurIFAC
    {
        
        public AdministrateurIFACClient()
        {
        }
        
        public AdministrateurIFACClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public AdministrateurIFACClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AdministrateurIFACClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AdministrateurIFACClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WebsBO.AdministrateurBO SelectById(int pAdministrateurId)
        {
            return base.Channel.SelectById(pAdministrateurId);
        }
        
        public System.IAsyncResult BeginSelectById(int pAdministrateurId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectById(pAdministrateurId, callback, asyncState);
        }
        
        public WebsBO.AdministrateurBO EndSelectById(System.IAsyncResult result)
        {
            return base.Channel.EndSelectById(result);
        }
    }
}
