//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WebsIFAC/ClientIFAC", ConfigurationName="WCF.Proxies.ClientIFAC")]
    public interface ClientIFAC
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/ClientIFAC/ClientIFAC/SelectAll", ReplyAction="urn:WebsIFAC/ClientIFAC/ClientIFAC/SelectAllResponse")]
        System.Collections.Generic.List<WebsBO.ClientBO> SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/ClientIFAC/ClientIFAC/SelectAll", ReplyAction="urn:WebsIFAC/ClientIFAC/ClientIFAC/SelectAllResponse")]
        System.IAsyncResult BeginSelectAll(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.ClientBO> EndSelectAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/ClientIFAC/ClientIFAC/SelectById", ReplyAction="urn:WebsIFAC/ClientIFAC/ClientIFAC/SelectByIdResponse")]
        WebsBO.ClientBO SelectById(int pId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/ClientIFAC/ClientIFAC/SelectById", ReplyAction="urn:WebsIFAC/ClientIFAC/ClientIFAC/SelectByIdResponse")]
        System.IAsyncResult BeginSelectById(int pId, System.AsyncCallback callback, object asyncState);
        
        WebsBO.ClientBO EndSelectById(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientIFACChannel : WCF.Proxies.ClientIFAC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientIFACClient : System.ServiceModel.ClientBase<WCF.Proxies.ClientIFAC>, WCF.Proxies.ClientIFAC
    {
        
        public ClientIFACClient()
        {
        }
        
        public ClientIFACClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ClientIFACClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ClientIFACClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ClientIFACClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<WebsBO.ClientBO> SelectAll()
        {
            return base.Channel.SelectAll();
        }
        
        public System.IAsyncResult BeginSelectAll(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectAll(callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.ClientBO> EndSelectAll(System.IAsyncResult result)
        {
            return base.Channel.EndSelectAll(result);
        }
        
        public WebsBO.ClientBO SelectById(int pId)
        {
            return base.Channel.SelectById(pId);
        }
        
        public System.IAsyncResult BeginSelectById(int pId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectById(pId, callback, asyncState);
        }
        
        public WebsBO.ClientBO EndSelectById(System.IAsyncResult result)
        {
            return base.Channel.EndSelectById(result);
        }
    }
}
