//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WebsIFAC/DemandeReservationIFAC", ConfigurationName="WCF.Proxies.DemandeReservationIFAC")]
    public interface DemandeReservationIFAC
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/SelectById", ReplyAction="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/SelectByIdResponse")]
        WebsBO.DemandeReservationBO SelectById(string token, int pDemandeReservationId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/SelectById", ReplyAction="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/SelectByIdResponse")]
        System.IAsyncResult BeginSelectById(string token, int pDemandeReservationId, System.AsyncCallback callback, object asyncState);
        
        WebsBO.DemandeReservationBO EndSelectById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/SelectAll", ReplyAction="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/SelectAllResponse")]
        System.Collections.Generic.List<WebsBO.DemandeReservationBO> SelectAll(string token);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/SelectAll", ReplyAction="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/SelectAllResponse")]
        System.IAsyncResult BeginSelectAll(string token, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.DemandeReservationBO> EndSelectAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/SelectNewByClient", ReplyAction="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/SelectNewByClientRespo" +
            "nse")]
        System.Collections.Generic.List<WebsBO.DemandeReservationBO> SelectNewByClient(string token, WebsBO.ClientBO pClient);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/SelectNewByClient", ReplyAction="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/SelectNewByClientRespo" +
            "nse")]
        System.IAsyncResult BeginSelectNewByClient(string token, WebsBO.ClientBO pClient, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.DemandeReservationBO> EndSelectNewByClient(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/SelectOldByClient", ReplyAction="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/SelectOldByClientRespo" +
            "nse")]
        System.Collections.Generic.List<WebsBO.DemandeReservationBO> SelectOldByClient(string token, WebsBO.ClientBO pClient);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/SelectOldByClient", ReplyAction="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/SelectOldByClientRespo" +
            "nse")]
        System.IAsyncResult BeginSelectOldByClient(string token, WebsBO.ClientBO pClient, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.DemandeReservationBO> EndSelectOldByClient(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/InsertDemandeReservati" +
            "on", ReplyAction="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/InsertDemandeReservati" +
            "onResponse")]
        WebsBO.DemandeReservationBO InsertDemandeReservation(string token, WebsBO.DemandeReservationBO pDemandeReservation);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/InsertDemandeReservati" +
            "on", ReplyAction="urn:WebsIFAC/DemandeReservationIFAC/DemandeReservationIFAC/InsertDemandeReservati" +
            "onResponse")]
        System.IAsyncResult BeginInsertDemandeReservation(string token, WebsBO.DemandeReservationBO pDemandeReservation, System.AsyncCallback callback, object asyncState);
        
        WebsBO.DemandeReservationBO EndInsertDemandeReservation(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DemandeReservationIFACChannel : WCF.Proxies.DemandeReservationIFAC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DemandeReservationIFACClient : System.ServiceModel.ClientBase<WCF.Proxies.DemandeReservationIFAC>, WCF.Proxies.DemandeReservationIFAC
    {
        
        public DemandeReservationIFACClient()
        {
        }
        
        public DemandeReservationIFACClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public DemandeReservationIFACClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DemandeReservationIFACClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DemandeReservationIFACClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WebsBO.DemandeReservationBO SelectById(string token, int pDemandeReservationId)
        {
            return base.Channel.SelectById(token, pDemandeReservationId);
        }
        
        public System.IAsyncResult BeginSelectById(string token, int pDemandeReservationId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectById(token, pDemandeReservationId, callback, asyncState);
        }
        
        public WebsBO.DemandeReservationBO EndSelectById(System.IAsyncResult result)
        {
            return base.Channel.EndSelectById(result);
        }
        
        public System.Collections.Generic.List<WebsBO.DemandeReservationBO> SelectAll(string token)
        {
            return base.Channel.SelectAll(token);
        }
        
        public System.IAsyncResult BeginSelectAll(string token, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectAll(token, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.DemandeReservationBO> EndSelectAll(System.IAsyncResult result)
        {
            return base.Channel.EndSelectAll(result);
        }
        
        public System.Collections.Generic.List<WebsBO.DemandeReservationBO> SelectNewByClient(string token, WebsBO.ClientBO pClient)
        {
            return base.Channel.SelectNewByClient(token, pClient);
        }
        
        public System.IAsyncResult BeginSelectNewByClient(string token, WebsBO.ClientBO pClient, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectNewByClient(token, pClient, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.DemandeReservationBO> EndSelectNewByClient(System.IAsyncResult result)
        {
            return base.Channel.EndSelectNewByClient(result);
        }
        
        public System.Collections.Generic.List<WebsBO.DemandeReservationBO> SelectOldByClient(string token, WebsBO.ClientBO pClient)
        {
            return base.Channel.SelectOldByClient(token, pClient);
        }
        
        public System.IAsyncResult BeginSelectOldByClient(string token, WebsBO.ClientBO pClient, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectOldByClient(token, pClient, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.DemandeReservationBO> EndSelectOldByClient(System.IAsyncResult result)
        {
            return base.Channel.EndSelectOldByClient(result);
        }
        
        public WebsBO.DemandeReservationBO InsertDemandeReservation(string token, WebsBO.DemandeReservationBO pDemandeReservation)
        {
            return base.Channel.InsertDemandeReservation(token, pDemandeReservation);
        }
        
        public System.IAsyncResult BeginInsertDemandeReservation(string token, WebsBO.DemandeReservationBO pDemandeReservation, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginInsertDemandeReservation(token, pDemandeReservation, callback, asyncState);
        }
        
        public WebsBO.DemandeReservationBO EndInsertDemandeReservation(System.IAsyncResult result)
        {
            return base.Channel.EndInsertDemandeReservation(result);
        }
    }
}
