//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WebsIFAC/EmpruntIFAC", ConfigurationName="WCF.Proxies.EmpruntIFAC")]
    public interface EmpruntIFAC
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/SelectAll", ReplyAction="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/SelectAllResponse")]
        System.Collections.Generic.List<WebsBO.EmpruntBO> SelectAll(string Token);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/SelectAll", ReplyAction="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/SelectAllResponse")]
        System.IAsyncResult BeginSelectAll(string Token, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.EmpruntBO> EndSelectAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/SelectEmpruntById", ReplyAction="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/SelectEmpruntByIdResponse")]
        WebsBO.EmpruntBO SelectEmpruntById(string Token, int pId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/SelectEmpruntById", ReplyAction="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/SelectEmpruntByIdResponse")]
        System.IAsyncResult BeginSelectEmpruntById(string Token, int pId, System.AsyncCallback callback, object asyncState);
        
        WebsBO.EmpruntBO EndSelectEmpruntById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/InsertEmpruntFromReservation", ReplyAction="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/InsertEmpruntFromReservationResponse")]
        WebsBO.EmpruntBO InsertEmpruntFromReservation(string Token, int pReservationId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/InsertEmpruntFromReservation", ReplyAction="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/InsertEmpruntFromReservationResponse")]
        System.IAsyncResult BeginInsertEmpruntFromReservation(string Token, int pReservationId, System.AsyncCallback callback, object asyncState);
        
        WebsBO.EmpruntBO EndInsertEmpruntFromReservation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/InsertEmprunt", ReplyAction="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/InsertEmpruntResponse")]
        WebsBO.EmpruntBO InsertEmprunt(string Token, int pBibliothequeId, int pPersonneId, int pLivreId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/InsertEmprunt", ReplyAction="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/InsertEmpruntResponse")]
        System.IAsyncResult BeginInsertEmprunt(string Token, int pBibliothequeId, int pPersonneId, int pLivreId, System.AsyncCallback callback, object asyncState);
        
        WebsBO.EmpruntBO EndInsertEmprunt(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/InsertRetour", ReplyAction="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/InsertRetourResponse")]
        WebsBO.EmpruntBO InsertRetour(string Token, int pLivreId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/InsertRetour", ReplyAction="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/InsertRetourResponse")]
        System.IAsyncResult BeginInsertRetour(string Token, int pLivreId, System.AsyncCallback callback, object asyncState);
        
        WebsBO.EmpruntBO EndInsertRetour(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/InsertAnnul", ReplyAction="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/InsertAnnulResponse")]
        WebsBO.EmpruntBO InsertAnnul(string Token, int pLivreId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/InsertAnnul", ReplyAction="urn:WebsIFAC/EmpruntIFAC/EmpruntIFAC/InsertAnnulResponse")]
        System.IAsyncResult BeginInsertAnnul(string Token, int pLivreId, System.AsyncCallback callback, object asyncState);
        
        WebsBO.EmpruntBO EndInsertAnnul(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmpruntIFACChannel : WCF.Proxies.EmpruntIFAC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpruntIFACClient : System.ServiceModel.ClientBase<WCF.Proxies.EmpruntIFAC>, WCF.Proxies.EmpruntIFAC
    {
        
        public EmpruntIFACClient()
        {
        }
        
        public EmpruntIFACClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public EmpruntIFACClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public EmpruntIFACClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public EmpruntIFACClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<WebsBO.EmpruntBO> SelectAll(string Token)
        {
            return base.Channel.SelectAll(Token);
        }
        
        public System.IAsyncResult BeginSelectAll(string Token, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectAll(Token, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.EmpruntBO> EndSelectAll(System.IAsyncResult result)
        {
            return base.Channel.EndSelectAll(result);
        }
        
        public WebsBO.EmpruntBO SelectEmpruntById(string Token, int pId)
        {
            return base.Channel.SelectEmpruntById(Token, pId);
        }
        
        public System.IAsyncResult BeginSelectEmpruntById(string Token, int pId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectEmpruntById(Token, pId, callback, asyncState);
        }
        
        public WebsBO.EmpruntBO EndSelectEmpruntById(System.IAsyncResult result)
        {
            return base.Channel.EndSelectEmpruntById(result);
        }
        
        public WebsBO.EmpruntBO InsertEmpruntFromReservation(string Token, int pReservationId)
        {
            return base.Channel.InsertEmpruntFromReservation(Token, pReservationId);
        }
        
        public System.IAsyncResult BeginInsertEmpruntFromReservation(string Token, int pReservationId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginInsertEmpruntFromReservation(Token, pReservationId, callback, asyncState);
        }
        
        public WebsBO.EmpruntBO EndInsertEmpruntFromReservation(System.IAsyncResult result)
        {
            return base.Channel.EndInsertEmpruntFromReservation(result);
        }
        
        public WebsBO.EmpruntBO InsertEmprunt(string Token, int pBibliothequeId, int pPersonneId, int pLivreId)
        {
            return base.Channel.InsertEmprunt(Token, pBibliothequeId, pPersonneId, pLivreId);
        }
        
        public System.IAsyncResult BeginInsertEmprunt(string Token, int pBibliothequeId, int pPersonneId, int pLivreId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginInsertEmprunt(Token, pBibliothequeId, pPersonneId, pLivreId, callback, asyncState);
        }
        
        public WebsBO.EmpruntBO EndInsertEmprunt(System.IAsyncResult result)
        {
            return base.Channel.EndInsertEmprunt(result);
        }
        
        public WebsBO.EmpruntBO InsertRetour(string Token, int pLivreId)
        {
            return base.Channel.InsertRetour(Token, pLivreId);
        }
        
        public System.IAsyncResult BeginInsertRetour(string Token, int pLivreId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginInsertRetour(Token, pLivreId, callback, asyncState);
        }
        
        public WebsBO.EmpruntBO EndInsertRetour(System.IAsyncResult result)
        {
            return base.Channel.EndInsertRetour(result);
        }
        
        public WebsBO.EmpruntBO InsertAnnul(string Token, int pLivreId)
        {
            return base.Channel.InsertAnnul(Token, pLivreId);
        }
        
        public System.IAsyncResult BeginInsertAnnul(string Token, int pLivreId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginInsertAnnul(Token, pLivreId, callback, asyncState);
        }
        
        public WebsBO.EmpruntBO EndInsertAnnul(System.IAsyncResult result)
        {
            return base.Channel.EndInsertAnnul(result);
        }
    }
}
