//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="uri:WebsIFAC/LivreStatusIFAC", ConfigurationName="WCF.Proxies.LivreStatusIFAC")]
    public interface LivreStatusIFAC
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="uri:WebsIFAC/LivreStatusIFAC/LivreStatusIFAC/SelectAll", ReplyAction="uri:WebsIFAC/LivreStatusIFAC/LivreStatusIFAC/SelectAllResponse")]
        System.Collections.Generic.List<WebsBO.LivreStatusBO> SelectAll(string Token);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="uri:WebsIFAC/LivreStatusIFAC/LivreStatusIFAC/SelectAll", ReplyAction="uri:WebsIFAC/LivreStatusIFAC/LivreStatusIFAC/SelectAllResponse")]
        System.IAsyncResult BeginSelectAll(string Token, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.LivreStatusBO> EndSelectAll(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LivreStatusIFACChannel : WCF.Proxies.LivreStatusIFAC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LivreStatusIFACClient : System.ServiceModel.ClientBase<WCF.Proxies.LivreStatusIFAC>, WCF.Proxies.LivreStatusIFAC
    {
        
        public LivreStatusIFACClient()
        {
        }
        
        public LivreStatusIFACClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public LivreStatusIFACClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public LivreStatusIFACClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public LivreStatusIFACClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<WebsBO.LivreStatusBO> SelectAll(string Token)
        {
            return base.Channel.SelectAll(Token);
        }
        
        public System.IAsyncResult BeginSelectAll(string Token, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectAll(Token, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.LivreStatusBO> EndSelectAll(System.IAsyncResult result)
        {
            return base.Channel.EndSelectAll(result);
        }
    }
}
