//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WebsIFAC/LivreIFAC", ConfigurationName="WCF.Proxies.LivreIFAC")]
    public interface LivreIFAC
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/LivreIFAC/LivreIFAC/SelectAll", ReplyAction="urn:WebsIFAC/LivreIFAC/LivreIFAC/SelectAllResponse")]
        System.Collections.Generic.List<WebsBO.LivreBO> SelectAll(string token);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/LivreIFAC/LivreIFAC/SelectAll", ReplyAction="urn:WebsIFAC/LivreIFAC/LivreIFAC/SelectAllResponse")]
        System.IAsyncResult BeginSelectAll(string token, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.LivreBO> EndSelectAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/LivreIFAC/LivreIFAC/SelectByInfo", ReplyAction="urn:WebsIFAC/LivreIFAC/LivreIFAC/SelectByInfoResponse")]
        System.Collections.Generic.List<WebsBO.LivreBO> SelectByInfo(string token, string pLivreInfo, int pBibliothequeId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/LivreIFAC/LivreIFAC/SelectByInfo", ReplyAction="urn:WebsIFAC/LivreIFAC/LivreIFAC/SelectByInfoResponse")]
        System.IAsyncResult BeginSelectByInfo(string token, string pLivreInfo, int pBibliothequeId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.LivreBO> EndSelectByInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/LivreIFAC/LivreIFAC/SelectByBibliotheque", ReplyAction="urn:WebsIFAC/LivreIFAC/LivreIFAC/SelectByBibliothequeResponse")]
        System.Collections.Generic.List<WebsBO.LivreBO> SelectByBibliotheque(string token, WebsBO.BibliothequeBO pBibliotheque);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/LivreIFAC/LivreIFAC/SelectByBibliotheque", ReplyAction="urn:WebsIFAC/LivreIFAC/LivreIFAC/SelectByBibliothequeResponse")]
        System.IAsyncResult BeginSelectByBibliotheque(string token, WebsBO.BibliothequeBO pBibliotheque, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.LivreBO> EndSelectByBibliotheque(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/LivreIFAC/LivreIFAC/SelectFicheLivreForClientByLivreId", ReplyAction="urn:WebsIFAC/LivreIFAC/LivreIFAC/SelectFicheLivreForClientByLivreIdResponse")]
        WebsBO.FicheLivreBO SelectFicheLivreForClientByLivreId(string token, int pClientId, int pLivreId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/LivreIFAC/LivreIFAC/SelectFicheLivreForClientByLivreId", ReplyAction="urn:WebsIFAC/LivreIFAC/LivreIFAC/SelectFicheLivreForClientByLivreIdResponse")]
        System.IAsyncResult BeginSelectFicheLivreForClientByLivreId(string token, int pClientId, int pLivreId, System.AsyncCallback callback, object asyncState);
        
        WebsBO.FicheLivreBO EndSelectFicheLivreForClientByLivreId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/LivreIFAC/LivreIFAC/InsertLivre", ReplyAction="urn:WebsIFAC/LivreIFAC/LivreIFAC/InsertLivreResponse")]
        WebsBO.LivreBO InsertLivre(string token, WebsBO.LivreBO pObjLivre, int pAdministrateurId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/LivreIFAC/LivreIFAC/InsertLivre", ReplyAction="urn:WebsIFAC/LivreIFAC/LivreIFAC/InsertLivreResponse")]
        System.IAsyncResult BeginInsertLivre(string token, WebsBO.LivreBO pObjLivre, int pAdministrateurId, System.AsyncCallback callback, object asyncState);
        
        WebsBO.LivreBO EndInsertLivre(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LivreIFACChannel : WCF.Proxies.LivreIFAC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LivreIFACClient : System.ServiceModel.ClientBase<WCF.Proxies.LivreIFAC>, WCF.Proxies.LivreIFAC
    {
        
        public LivreIFACClient()
        {
        }
        
        public LivreIFACClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public LivreIFACClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public LivreIFACClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public LivreIFACClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<WebsBO.LivreBO> SelectAll(string token)
        {
            return base.Channel.SelectAll(token);
        }
        
        public System.IAsyncResult BeginSelectAll(string token, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectAll(token, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.LivreBO> EndSelectAll(System.IAsyncResult result)
        {
            return base.Channel.EndSelectAll(result);
        }
        
        public System.Collections.Generic.List<WebsBO.LivreBO> SelectByInfo(string token, string pLivreInfo, int pBibliothequeId)
        {
            return base.Channel.SelectByInfo(token, pLivreInfo, pBibliothequeId);
        }
        
        public System.IAsyncResult BeginSelectByInfo(string token, string pLivreInfo, int pBibliothequeId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectByInfo(token, pLivreInfo, pBibliothequeId, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.LivreBO> EndSelectByInfo(System.IAsyncResult result)
        {
            return base.Channel.EndSelectByInfo(result);
        }
        
        public System.Collections.Generic.List<WebsBO.LivreBO> SelectByBibliotheque(string token, WebsBO.BibliothequeBO pBibliotheque)
        {
            return base.Channel.SelectByBibliotheque(token, pBibliotheque);
        }
        
        public System.IAsyncResult BeginSelectByBibliotheque(string token, WebsBO.BibliothequeBO pBibliotheque, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectByBibliotheque(token, pBibliotheque, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.LivreBO> EndSelectByBibliotheque(System.IAsyncResult result)
        {
            return base.Channel.EndSelectByBibliotheque(result);
        }
        
        public WebsBO.FicheLivreBO SelectFicheLivreForClientByLivreId(string token, int pClientId, int pLivreId)
        {
            return base.Channel.SelectFicheLivreForClientByLivreId(token, pClientId, pLivreId);
        }
        
        public System.IAsyncResult BeginSelectFicheLivreForClientByLivreId(string token, int pClientId, int pLivreId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectFicheLivreForClientByLivreId(token, pClientId, pLivreId, callback, asyncState);
        }
        
        public WebsBO.FicheLivreBO EndSelectFicheLivreForClientByLivreId(System.IAsyncResult result)
        {
            return base.Channel.EndSelectFicheLivreForClientByLivreId(result);
        }
        
        public WebsBO.LivreBO InsertLivre(string token, WebsBO.LivreBO pObjLivre, int pAdministrateurId)
        {
            return base.Channel.InsertLivre(token, pObjLivre, pAdministrateurId);
        }
        
        public System.IAsyncResult BeginInsertLivre(string token, WebsBO.LivreBO pObjLivre, int pAdministrateurId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginInsertLivre(token, pObjLivre, pAdministrateurId, callback, asyncState);
        }
        
        public WebsBO.LivreBO EndInsertLivre(System.IAsyncResult result)
        {
            return base.Channel.EndInsertLivre(result);
        }
    }
}
