//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WebsIFAC/LocationIFAC", ConfigurationName="WCF.Proxies.LocationIFAC")]
    public interface LocationIFAC
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/LocationIFAC/LocationIFAC/SelectAll", ReplyAction="urn:WebsIFAC/LocationIFAC/LocationIFAC/SelectAllResponse")]
        System.Collections.Generic.List<WebsBO.LocationBO> SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/LocationIFAC/LocationIFAC/SelectAll", ReplyAction="urn:WebsIFAC/LocationIFAC/LocationIFAC/SelectAllResponse")]
        System.IAsyncResult BeginSelectAll(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.LocationBO> EndSelectAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/LocationIFAC/LocationIFAC/SelectLocationById", ReplyAction="urn:WebsIFAC/LocationIFAC/LocationIFAC/SelectLocationByIdResponse")]
        WebsBO.LocationBO SelectLocationById(int pId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/LocationIFAC/LocationIFAC/SelectLocationById", ReplyAction="urn:WebsIFAC/LocationIFAC/LocationIFAC/SelectLocationByIdResponse")]
        System.IAsyncResult BeginSelectLocationById(int pId, System.AsyncCallback callback, object asyncState);
        
        WebsBO.LocationBO EndSelectLocationById(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LocationIFACChannel : WCF.Proxies.LocationIFAC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocationIFACClient : System.ServiceModel.ClientBase<WCF.Proxies.LocationIFAC>, WCF.Proxies.LocationIFAC
    {
        
        public LocationIFACClient()
        {
        }
        
        public LocationIFACClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public LocationIFACClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public LocationIFACClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public LocationIFACClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<WebsBO.LocationBO> SelectAll()
        {
            return base.Channel.SelectAll();
        }
        
        public System.IAsyncResult BeginSelectAll(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectAll(callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.LocationBO> EndSelectAll(System.IAsyncResult result)
        {
            return base.Channel.EndSelectAll(result);
        }
        
        public WebsBO.LocationBO SelectLocationById(int pId)
        {
            return base.Channel.SelectLocationById(pId);
        }
        
        public System.IAsyncResult BeginSelectLocationById(int pId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectLocationById(pId, callback, asyncState);
        }
        
        public WebsBO.LocationBO EndSelectLocationById(System.IAsyncResult result)
        {
            return base.Channel.EndSelectLocationById(result);
        }
    }
}
