//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WebsIFAC/RefLivreIFAC", ConfigurationName="WCF.Proxies.RefLivreIFAC")]
    public interface RefLivreIFAC
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/FindAmazonRefByISBN", ReplyAction="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/FindAmazonRefByISBNResponse")]
        System.Collections.Generic.List<WebsBO.RefLivreBO> FindAmazonRefByISBN(string Token, System.Collections.Generic.List<string> pISBNs);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/FindAmazonRefByISBN", ReplyAction="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/FindAmazonRefByISBNResponse")]
        System.IAsyncResult BeginFindAmazonRefByISBN(string Token, System.Collections.Generic.List<string> pISBNs, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.RefLivreBO> EndFindAmazonRefByISBN(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/FindAmazonRefByTitle", ReplyAction="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/FindAmazonRefByTitleResponse")]
        System.Collections.Generic.List<WebsBO.RefLivreBO> FindAmazonRefByTitle(string Token, string pTitle);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/FindAmazonRefByTitle", ReplyAction="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/FindAmazonRefByTitleResponse")]
        System.IAsyncResult BeginFindAmazonRefByTitle(string Token, string pTitle, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.RefLivreBO> EndFindAmazonRefByTitle(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/SelectAll", ReplyAction="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/SelectAllResponse")]
        System.Collections.Generic.List<WebsBO.RefLivreBO> SelectAll(string Token);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/SelectAll", ReplyAction="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/SelectAllResponse")]
        System.IAsyncResult BeginSelectAll(string Token, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.RefLivreBO> EndSelectAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/SelectByTitre", ReplyAction="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/SelectByTitreResponse")]
        System.Collections.Generic.List<WebsBO.RefLivreBO> SelectByTitre(string Token, string pTitre);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/SelectByTitre", ReplyAction="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/SelectByTitreResponse")]
        System.IAsyncResult BeginSelectByTitre(string Token, string pTitre, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.RefLivreBO> EndSelectByTitre(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/SelectByISBN", ReplyAction="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/SelectByISBNResponse")]
        System.Collections.Generic.List<WebsBO.RefLivreBO> SelectByISBN(string Token, string pISBN);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/SelectByISBN", ReplyAction="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/SelectByISBNResponse")]
        System.IAsyncResult BeginSelectByISBN(string Token, string pISBN, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.RefLivreBO> EndSelectByISBN(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/InsertLivre", ReplyAction="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/InsertLivreResponse")]
        System.Collections.Generic.List<WebsBO.RefLivreBO> InsertLivre(string Token, string pISBN, string pTitre, string pDescription, string pAuteur, string pLangue, string pEditeur, System.DateTime pPublished, string pImageUrl);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/InsertLivre", ReplyAction="urn:WebsIFAC/RefLivreIFAC/RefLivreIFAC/InsertLivreResponse")]
        System.IAsyncResult BeginInsertLivre(string Token, string pISBN, string pTitre, string pDescription, string pAuteur, string pLangue, string pEditeur, System.DateTime pPublished, string pImageUrl, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.RefLivreBO> EndInsertLivre(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RefLivreIFACChannel : WCF.Proxies.RefLivreIFAC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RefLivreIFACClient : System.ServiceModel.ClientBase<WCF.Proxies.RefLivreIFAC>, WCF.Proxies.RefLivreIFAC
    {
        
        public RefLivreIFACClient()
        {
        }
        
        public RefLivreIFACClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public RefLivreIFACClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RefLivreIFACClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RefLivreIFACClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<WebsBO.RefLivreBO> FindAmazonRefByISBN(string Token, System.Collections.Generic.List<string> pISBNs)
        {
            return base.Channel.FindAmazonRefByISBN(Token, pISBNs);
        }
        
        public System.IAsyncResult BeginFindAmazonRefByISBN(string Token, System.Collections.Generic.List<string> pISBNs, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginFindAmazonRefByISBN(Token, pISBNs, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.RefLivreBO> EndFindAmazonRefByISBN(System.IAsyncResult result)
        {
            return base.Channel.EndFindAmazonRefByISBN(result);
        }
        
        public System.Collections.Generic.List<WebsBO.RefLivreBO> FindAmazonRefByTitle(string Token, string pTitle)
        {
            return base.Channel.FindAmazonRefByTitle(Token, pTitle);
        }
        
        public System.IAsyncResult BeginFindAmazonRefByTitle(string Token, string pTitle, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginFindAmazonRefByTitle(Token, pTitle, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.RefLivreBO> EndFindAmazonRefByTitle(System.IAsyncResult result)
        {
            return base.Channel.EndFindAmazonRefByTitle(result);
        }
        
        public System.Collections.Generic.List<WebsBO.RefLivreBO> SelectAll(string Token)
        {
            return base.Channel.SelectAll(Token);
        }
        
        public System.IAsyncResult BeginSelectAll(string Token, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectAll(Token, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.RefLivreBO> EndSelectAll(System.IAsyncResult result)
        {
            return base.Channel.EndSelectAll(result);
        }
        
        public System.Collections.Generic.List<WebsBO.RefLivreBO> SelectByTitre(string Token, string pTitre)
        {
            return base.Channel.SelectByTitre(Token, pTitre);
        }
        
        public System.IAsyncResult BeginSelectByTitre(string Token, string pTitre, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectByTitre(Token, pTitre, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.RefLivreBO> EndSelectByTitre(System.IAsyncResult result)
        {
            return base.Channel.EndSelectByTitre(result);
        }
        
        public System.Collections.Generic.List<WebsBO.RefLivreBO> SelectByISBN(string Token, string pISBN)
        {
            return base.Channel.SelectByISBN(Token, pISBN);
        }
        
        public System.IAsyncResult BeginSelectByISBN(string Token, string pISBN, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectByISBN(Token, pISBN, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.RefLivreBO> EndSelectByISBN(System.IAsyncResult result)
        {
            return base.Channel.EndSelectByISBN(result);
        }
        
        public System.Collections.Generic.List<WebsBO.RefLivreBO> InsertLivre(string Token, string pISBN, string pTitre, string pDescription, string pAuteur, string pLangue, string pEditeur, System.DateTime pPublished, string pImageUrl)
        {
            return base.Channel.InsertLivre(Token, pISBN, pTitre, pDescription, pAuteur, pLangue, pEditeur, pPublished, pImageUrl);
        }
        
        public System.IAsyncResult BeginInsertLivre(string Token, string pISBN, string pTitre, string pDescription, string pAuteur, string pLangue, string pEditeur, System.DateTime pPublished, string pImageUrl, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginInsertLivre(Token, pISBN, pTitre, pDescription, pAuteur, pLangue, pEditeur, pPublished, pImageUrl, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.RefLivreBO> EndInsertLivre(System.IAsyncResult result)
        {
            return base.Channel.EndInsertLivre(result);
        }
    }
}
