//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WebsIFAC/ReservationIFAC", ConfigurationName="WCF.Proxies.ReservationIFAC")]
    public interface ReservationIFAC
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectAll", ReplyAction="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectAllResponse")]
        System.Collections.Generic.List<WebsBO.ReservationBO> SelectAll(string token);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectAll", ReplyAction="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectAllResponse")]
        System.IAsyncResult BeginSelectAll(string token, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.ReservationBO> EndSelectAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectReservationById", ReplyAction="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectReservationByIdResponse")]
        WebsBO.ReservationBO SelectReservationById(string token, int pId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectReservationById", ReplyAction="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectReservationByIdResponse")]
        System.IAsyncResult BeginSelectReservationById(string token, int pId, System.AsyncCallback callback, object asyncState);
        
        WebsBO.ReservationBO EndSelectReservationById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectEnCoursValidByClientId", ReplyAction="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectEnCoursValidByClientIdResponse" +
            "")]
        System.Collections.Generic.List<WebsBO.ReservationBO> SelectEnCoursValidByClientId(string token, int pClientId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectEnCoursValidByClientId", ReplyAction="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectEnCoursValidByClientIdResponse" +
            "")]
        System.IAsyncResult BeginSelectEnCoursValidByClientId(string token, int pClientId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.ReservationBO> EndSelectEnCoursValidByClientId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectEnCoursValidByInfo", ReplyAction="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectEnCoursValidByInfoResponse")]
        System.Collections.Generic.List<WebsBO.ReservationBO> SelectEnCoursValidByInfo(string token, string pInfo);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectEnCoursValidByInfo", ReplyAction="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectEnCoursValidByInfoResponse")]
        System.IAsyncResult BeginSelectEnCoursValidByInfo(string token, string pInfo, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.ReservationBO> EndSelectEnCoursValidByInfo(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReservationIFACChannel : WCF.Proxies.ReservationIFAC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservationIFACClient : System.ServiceModel.ClientBase<WCF.Proxies.ReservationIFAC>, WCF.Proxies.ReservationIFAC
    {
        
        public ReservationIFACClient()
        {
        }
        
        public ReservationIFACClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ReservationIFACClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ReservationIFACClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ReservationIFACClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<WebsBO.ReservationBO> SelectAll(string token)
        {
            return base.Channel.SelectAll(token);
        }
        
        public System.IAsyncResult BeginSelectAll(string token, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectAll(token, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.ReservationBO> EndSelectAll(System.IAsyncResult result)
        {
            return base.Channel.EndSelectAll(result);
        }
        
        public WebsBO.ReservationBO SelectReservationById(string token, int pId)
        {
            return base.Channel.SelectReservationById(token, pId);
        }
        
        public System.IAsyncResult BeginSelectReservationById(string token, int pId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectReservationById(token, pId, callback, asyncState);
        }
        
        public WebsBO.ReservationBO EndSelectReservationById(System.IAsyncResult result)
        {
            return base.Channel.EndSelectReservationById(result);
        }
        
        public System.Collections.Generic.List<WebsBO.ReservationBO> SelectEnCoursValidByClientId(string token, int pClientId)
        {
            return base.Channel.SelectEnCoursValidByClientId(token, pClientId);
        }
        
        public System.IAsyncResult BeginSelectEnCoursValidByClientId(string token, int pClientId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectEnCoursValidByClientId(token, pClientId, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.ReservationBO> EndSelectEnCoursValidByClientId(System.IAsyncResult result)
        {
            return base.Channel.EndSelectEnCoursValidByClientId(result);
        }
        
        public System.Collections.Generic.List<WebsBO.ReservationBO> SelectEnCoursValidByInfo(string token, string pInfo)
        {
            return base.Channel.SelectEnCoursValidByInfo(token, pInfo);
        }
        
        public System.IAsyncResult BeginSelectEnCoursValidByInfo(string token, string pInfo, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectEnCoursValidByInfo(token, pInfo, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.ReservationBO> EndSelectEnCoursValidByInfo(System.IAsyncResult result)
        {
            return base.Channel.EndSelectEnCoursValidByInfo(result);
        }
    }
}
