//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WebsIFAC/ReservationIFAC", ConfigurationName="WCF.Proxies.ReservationIFAC")]
    public interface ReservationIFAC
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectAll", ReplyAction="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectAllResponse")]
        System.Collections.Generic.List<WebsBO.ReservationBO> SelectAll(string Token);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectAll", ReplyAction="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectAllResponse")]
        System.IAsyncResult BeginSelectAll(string Token, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WebsBO.ReservationBO> EndSelectAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectReservationById", ReplyAction="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectReservationByIdResponse")]
        WebsBO.ReservationBO SelectReservationById(string Token, int pId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectReservationById", ReplyAction="urn:WebsIFAC/ReservationIFAC/ReservationIFAC/SelectReservationByIdResponse")]
        System.IAsyncResult BeginSelectReservationById(string Token, int pId, System.AsyncCallback callback, object asyncState);
        
        WebsBO.ReservationBO EndSelectReservationById(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReservationIFACChannel : WCF.Proxies.ReservationIFAC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservationIFACClient : System.ServiceModel.ClientBase<WCF.Proxies.ReservationIFAC>, WCF.Proxies.ReservationIFAC
    {
        
        public ReservationIFACClient()
        {
        }
        
        public ReservationIFACClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ReservationIFACClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ReservationIFACClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ReservationIFACClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<WebsBO.ReservationBO> SelectAll(string Token)
        {
            return base.Channel.SelectAll(Token);
        }
        
        public System.IAsyncResult BeginSelectAll(string Token, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectAll(Token, callback, asyncState);
        }
        
        public System.Collections.Generic.List<WebsBO.ReservationBO> EndSelectAll(System.IAsyncResult result)
        {
            return base.Channel.EndSelectAll(result);
        }
        
        public WebsBO.ReservationBO SelectReservationById(string Token, int pId)
        {
            return base.Channel.SelectReservationById(Token, pId);
        }
        
        public System.IAsyncResult BeginSelectReservationById(string Token, int pId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectReservationById(Token, pId, callback, asyncState);
        }
        
        public WebsBO.ReservationBO EndSelectReservationById(System.IAsyncResult result)
        {
            return base.Channel.EndSelectReservationById(result);
        }
    }
}
