//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WebsIFAC/SessionIFAC", ConfigurationName="WCF.Proxies.SessionIFAC")]
    public interface SessionIFAC
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/SessionIFAC/SessionIFAC/OpenSession", ReplyAction="urn:WebsIFAC/SessionIFAC/SessionIFAC/OpenSessionResponse")]
        WebsBO.SessionBO OpenSession(string pUsername, string pPassword);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/SessionIFAC/SessionIFAC/OpenSession", ReplyAction="urn:WebsIFAC/SessionIFAC/SessionIFAC/OpenSessionResponse")]
        System.IAsyncResult BeginOpenSession(string pUsername, string pPassword, System.AsyncCallback callback, object asyncState);
        
        WebsBO.SessionBO EndOpenSession(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SessionIFACChannel : WCF.Proxies.SessionIFAC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionIFACClient : System.ServiceModel.ClientBase<WCF.Proxies.SessionIFAC>, WCF.Proxies.SessionIFAC
    {
        
        public SessionIFACClient()
        {
        }
        
        public SessionIFACClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SessionIFACClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SessionIFACClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SessionIFACClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WebsBO.SessionBO OpenSession(string pUsername, string pPassword)
        {
            return base.Channel.OpenSession(pUsername, pPassword);
        }
        
        public System.IAsyncResult BeginOpenSession(string pUsername, string pPassword, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginOpenSession(pUsername, pPassword, callback, asyncState);
        }
        
        public WebsBO.SessionBO EndOpenSession(System.IAsyncResult result)
        {
            return base.Channel.EndOpenSession(result);
        }
    }
}
