//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WebsIFAC/SessionManagerIFAC", ConfigurationName="WCF.Proxies.SessionManagerIFAC")]
    public interface SessionManagerIFAC
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebsIFAC/SessionManagerIFAC/SessionManagerIFAC/OpenSession", ReplyAction="urn:WebsIFAC/SessionManagerIFAC/SessionManagerIFAC/OpenSessionResponse")]
        WebsBO.SessionManagerBO OpenSession(string pUsername, string pPassword);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WebsIFAC/SessionManagerIFAC/SessionManagerIFAC/OpenSession", ReplyAction="urn:WebsIFAC/SessionManagerIFAC/SessionManagerIFAC/OpenSessionResponse")]
        System.IAsyncResult BeginOpenSession(string pUsername, string pPassword, System.AsyncCallback callback, object asyncState);
        
        WebsBO.SessionManagerBO EndOpenSession(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SessionManagerIFACChannel : WCF.Proxies.SessionManagerIFAC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionManagerIFACClient : System.ServiceModel.ClientBase<WCF.Proxies.SessionManagerIFAC>, WCF.Proxies.SessionManagerIFAC
    {
        
        public SessionManagerIFACClient()
        {
        }
        
        public SessionManagerIFACClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SessionManagerIFACClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SessionManagerIFACClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SessionManagerIFACClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WebsBO.SessionManagerBO OpenSession(string pUsername, string pPassword)
        {
            return base.Channel.OpenSession(pUsername, pPassword);
        }
        
        public System.IAsyncResult BeginOpenSession(string pUsername, string pPassword, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginOpenSession(pUsername, pPassword, callback, asyncState);
        }
        
        public WebsBO.SessionManagerBO EndOpenSession(System.IAsyncResult result)
        {
            return base.Channel.EndOpenSession(result);
        }
    }
}
